local bar_bg = "#1a1b26"

return {
  "akinsho/bufferline.nvim",
  dependencies = "nvim-tree/nvim-web-devicons",
  version = "*",
  opts = {
    highlights = {
      fill                            = { bg = bar_bg },
      background                      = { bg = bar_bg },
      tab                             = { bg = bar_bg },
      tab_selected                    = { bg = bar_bg },
      tab_separator                   = { fg = bar_bg, bg = bar_bg },
      tab_separator_selected          = { fg = bar_bg, bg = bar_bg },
      tab_close                       = { bg = bar_bg },
      buffer                          = { bg = bar_bg, fg = "#9da4c8" },
      buffer_visible                  = { bg = bar_bg, fg = "#9da4c8" },
      buffer_selected                 = { bg = bar_bg, fg = "#9da4c8" },
      numbers                         = { bg = bar_bg },
      numbers_visible                 = { bg = bar_bg },
      numbers_selected                = { bg = bar_bg },
      diagnostic                      = { bg = bar_bg },
      diagnostic_visible              = { bg = bar_bg },
      diagnostic_selected             = { bg = bar_bg },
      hint                            = { bg = bar_bg },
      hint_visible                    = { bg = bar_bg },
      hint_selected                   = { bg = bar_bg },
      hint_diagnostic                 = { bg = bar_bg },
      hint_diagnostic_visible         = { bg = bar_bg },
      hint_diagnostic_selected        = { bg = bar_bg },
      info                            = { bg = bar_bg },
      info_visible                    = { bg = bar_bg },
      info_selected                   = { bg = bar_bg },
      info_diagnostic                 = { bg = bar_bg },
      info_diagnostic_visible         = { bg = bar_bg },
      info_diagnostic_selected        = { bg = bar_bg },
      warning                         = { bg = bar_bg },
      warning_visible                 = { bg = bar_bg },
      warning_selected                = { bg = bar_bg },
      warning_diagnostic              = { bg = bar_bg },
      warning_diagnostic_visible      = { bg = bar_bg },
      warning_diagnostic_selected     = { bg = bar_bg },
      error                           = { bg = bar_bg },
      error_visible                   = { bg = bar_bg },
      error_selected                  = { bg = bar_bg },
      error_diagnostic                = { bg = bar_bg },
      error_diagnostic_visible        = { bg = bar_bg },
      error_diagnostic_selected       = { bg = bar_bg },
      modified                        = { bg = bar_bg },
      modified_visible                = { bg = bar_bg },
      modified_selected               = { bg = bar_bg },
      duplicate                       = { bg = bar_bg },
      duplicate_visible               = { bg = bar_bg },
      duplicate_selected              = { bg = bar_bg },
      separator                       = { fg = bar_bg, bg = bar_bg },
      separator_visible               = { fg = bar_bg, bg = bar_bg },
      separator_selected              = { fg = bar_bg, bg = bar_bg },
      indicator_visible               = { fg = bar_bg, bg = bar_bg },
      indicator_selected              = { fg = bar_bg, bg = bar_bg },
      pick                            = { bg = bar_bg },
      pick_visible                    = { bg = bar_bg },
      pick_selected                   = { bg = bar_bg },
      offset_separator                = { fg = bar_bg, bg = bar_bg },
      trunc_marker                    = { bg = bar_bg },
    },
    options = {
      mode = "buffers",
      left_mouse_command = "buffer %d",
      right_mouse_command = "bdelete! %d",
      indicator = { style = "none" },
      separator_style = { ' ', ' ' },
      show_buffer_close_icons = false,
      show_close_icon = false,
      buffer_close_icons = false,
      modified_icon = " +",
      diagnostics = false,
      offsets = {
        {
          filetype = "NvimTree",
          text = "",
          highlight = "BufferLineFill",
          text_align = "left",
        },
      },
    },
  },
}
